# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 27 Jan 2010 22:45:39 +0000
*   @ALL 1
*	@0	1
*	@1	16
*	@2	16
*	@9	16



