<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: shiverz
 * Date: Wed, 10 Feb 2010 15:28:25 +0200
 */

$conf['title'] = 'The Kingdoms of Chaos - Wiki';
$conf['start'] = 'Introduction';
$conf['template'] = 'tkoc';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['authtype'] = 'smfauth';
$conf['superuser'] = '@1, @9';
$conf['htmlok'] = 1;
$conf['plugin']['translation']['translations'] = 'english, greek';
$conf['plugin']['translation']['translationns'] = 'language';
$conf['tpl']['monobook']['monobook_sitenotice'] = 0;
$conf['auth']['mysql']['charset'] = 'utf8';

// end auto-generated content
